### ISSUE TITLE
pip install pynacl 

### ISSUE THREAD

**Issue by AnujKuralkar** [holzschu/Carnets#155]
![install error image](https://user-images.githubusercontent.com/76731106/109949345-45895700-7d01-11eb-979a-f69a3c514196.jpeg)

**Comment by holzschu** [comment]
It makes sense, since pynacl is only a wrapper for the libsodium library, and the libsodium cannot be compiled at the user level (only pure python packages can be installed by the user, since there are no C compilers on iOS).

The crypto package is already installed, but I don't know if that answers your needs.
