### ISSUE TITLE
Enter key on Apple Smart keyboard folio not producing line break (possibly due to iOS 15 beta)

### ISSUE THREAD

**Issue by MaxPelly** [holzschu/Carnets#188]
Using the enter key on the smart keyboard folio while in a cell does not to produce a new line. Using the software keyboard enter key does however. Using the shift-enter combo on the smart keyboard does execute a cell, and the enter key behaves as expected in other apps.

To reproduce:

1. Place iPad in smart folio keyboard and dock
2. Open carnets plus
3. open a new jupyter notebook
4. tap a cell to enter edit mode
5. type a line of code
6. press enter for new line, **NOTHING HAPPENS**
7. press shift and enter to execute cell, cell executed as expected
8. reenter cell and bring up software keyboard
9. press enter on software keyboard, new line produced as expected

Specs:
iPad Pro (11-inch) (3rd generation) iOS 15 beta 2
English Smart keyboard folio
Carnets plus 1.5.8

**Comment by holzschu** [comment]
Hi, I have good news and bad news. 

The good news is that this issue is fixed if I compile Carnets with Xcode 13 beta. I have even submitted a build to Apple (for TestFlight, of course) compiled with Xcode beta where the issue is fixed.

The bad news is that the build is still waiting for approval (it was uploaded on July 13).

**Comment by MaxPelly** [comment]
Well thats mainly good, just wait on old apple now :(

**Comment by jonasspeiser** [comment]
Are there any news on the release of the fix yet?

**Comment by holzschu** [comment]
The Carnets version has been released on the AppStore. The Carnets-with-Scipy version is on TestFlight right now (https://testflight.apple.com/join/UbNIjkjp ), with a few more things to fix before an AppStore release. But since the big issue was getting a build accepted by Apple, it should now be a matter of days (compiling takes hours, uploading a build and getting it accepted by Apple each takes roughly a day, so nothing is fast in this development).
