### ISSUE TITLE
Cannot install pycryptodome (needed by pdfminer.six and pdf plumber)

### ISSUE THREAD

**Issue by ugopvn** [holzschu/Carnets#210]
Hi how can I install pycryptodome?

When I try, carnets get stuck at 'Prepa metadata (setup.py): started'

Thanks in advance for the help

**Comment by holzschu** [comment]
So, I've got bad news, good news and bad news.

The bad news is that you cannot install pycryptodome at the user level, because it contains components written in C. 
The good news is that pdfminer.six dropped the dependency on pycryptodome in July 2020, so "%pip install pdfminer.six" will work.
The bad news is that pdfplumber has a requirement for `pdfminer.six==20200517`, that is the last version before the change away from pycryptodome.

Looking at pdfplumber github repository, they have a `develop` branch, where they have already made the changes required to use `pdfminer.six==20211012`. You have several strategies available:
- wait for the next release of pdfplumber, which will drop the pycryptodome dependency.
- clone the pdfplumber repository, switch to the develop branch, then run "!python3 setup.py install ." to install the experimental version.

**Comment by ugopvn** [comment]
Thank you for the advice. The new pdfplumber 0.60 was released and everything works fine.
