### ISSUE TITLE
problem with download as html

### ISSUE THREAD

**Issue by minpj** [holzschu/Carnets#287]
Hi I’m using Carnets Plus with iPadOS 16.3.1. When I try to download jupyter notebook as .html file I always get the 500: internal server error. What is gong on？Thank you！

**Comment by holzschu** [comment]
Hi,
I ran some tests, and it’s related to writing permissions in the directory: if Carnets has writing access on the directory where the notebook is, it creates the HTML version. Without writing access, you get the “500: internal server error”, because the notebook conversion program was unable to create the HTML version.

**Comment by minpj** [comment]
I just realize that I should put my documents under the directory of Carnets. Thank you very much！

**Comment by holzschu** [comment]
You can put them in any directory, but you need to give Carnets the right to write files in that directory, using the "unlock folder" icon at the top right of the screen.

**Comment by minpj** [comment]
I see. Thanks again！发自我的 iPad在 2023年2月23日，16:28，Nicolas Holzschuch ***@***.***> 写道：﻿
You can put them in any directory, but you need to give Carnets the right to write files in that directory, using the "unlock folder" icon at the top right of the screen.
