### ISSUE TITLE
Older Version

### ISSUE THREAD

**Issue by RMurison** [holzschu/Carnets#35]
I’ve been using Carnets on my iPhone and it’s working wonderfully. I’ve got an old iPad that can only update to iOS 10.3, and was wondering if there’s any way to access an older version of the app that would be compatible. Many thanks!

**Comment by holzschu** [comment]
Hi, 
I’m terribly sorry, but Carnets has been restricted to iOS 11 and above since the beginning.
There are multiple reasons:
- first, we only compile for arm 64 bit processors (arm64 and arm7), which corresponds to iOS 11 ability.
- we use a lot of the file access API that was introduced in iOS 11. 
- we rely on many packages that are also restricted to iOS 11 and above.

**Comment by RMurison** [comment]
I understand, thanks so much.
