### ISSUE TITLE
Allow to link Files location

### ISSUE THREAD

**Issue by goerz** [holzschu/Carnets#52]
It would be great if Carnets could link arbitrary Files location. Currently, if I open notebooks from the Files app that are in a location outside of Carnet's sandbox, and those notebooks reference other files in the same folder, that won't work.

For example, I can open Juno's "Introductory Notebooks / 3.3 NumPy - File IO" in Carnets just fine, but it will fail to open the files from the data folder.

Ideally, I'd like to set up fixed linked locations that I don't have to reauthorize all the time (just like in in Working Copy, Texpad, and iA Writer, for example). I don't know if this kind of linking is compatible with having a Files view as the main UI (#51).  If not (or possibly in addition), Carnets should at least be able to "unlock" the current folder - Juno has this feature (the folder-lock symbol in the top right after opening a notebook from a non-sandbox location)

**Comment by holzschu** [comment]
I'll see what I can do. 
Currently, if you open a folder from the user interface inside Carnets, this folder and its entire content become authorised. Method:
- go to Files view (either start the app and browse, or go back to Files view from an open notebook) 
- click "Select" (top right)
- click on the disk on (or next to) the folder you want to open 
- click "Open", and you have a running file browser. All notebooks from inside this folder can access all data files from inside the folder. The folder permission is, if I remember correctly, permanent.

The ability to unlock the current folder without going to a Files browser is surprising. I am not aware of an existing API to allow this, but since it's been done, it must be feasible.

**Comment by goerz** [comment]
Yup, that works now, after having reinstalled Carnets (before, there was no Documents browser where I could open a folder).

This pretty much solves the problem, as far as I'm concerned. I'd consider the more permanent linked folders as highly optional, so feel free to close this unless you feel particularly inspired to implement this extra functionality.

**Comment by tomdmt** [comment]
This works well for local folders and folders on iCloud but doesn’t work with third party cloud storage services like box, which would be nice for collaboration

**Comment by pmeng360** [comment]
It doesn’t work for me; and I tried several time on various devices. Every time I click select (+), it creates a new notebook.

**Comment by holzschu** [comment]
You need to click on "Select", not on "+".

**Comment by pmeng360** [comment]
Thanks! It works like a charm.

**Comment by holzschu** [comment]
We will have the ability to unlock the current folder in the upcoming version 1.4.0 (soon).
