### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by oleksis** [holzschu/Carnets#83]
When I use multiprocessing module I get this error: 

/var/mobile/Containers/Data/Application/6ACBAC54-A47E-4DBF-A175-8CB3E8E8AC20/Library/lib/python3.7/multiprocessing/queues.py in <module>
     20 from queue import Empty, Full
     21 
---> 22 import _multiprocessing
     23 
     24 from . import connection

ModuleNotFoundError: No module named '_multiprocessing'

I use this notebook in Colaboratory https://colab.research.google.com/github/oleksis/notebooks/blob/master/pool_multiprocess_fib.ipynb and all work OK

What I need in Carnets for working with Multiprocessing CPU?

**Comment by holzschu** [comment]
The short answer is: "you can't use multiprocessing with Carnets". I'm sorry about that, but it is really too difficult to support.

The long answer is: multiprocessing in Python relies on multiple calls to `fork()`, with a pool of process and a queue for tasks to be executed. iOS does not have the `fork()` system call, so there is no way to make this work, and I don't think there is one.

Since most iPads have only 4 cores anyway (and some cores are already used by the system and the Jupyter server), I am not certain we would gain much processing power anyway.

**Comment by oleksis** [comment]
Thanks for help @holzschu and for Carnets
